-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 20:25:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`rooms` (
  `id` INT NOT NULL,
  `max-persons` INT NULL,
  `category` VARCHAR(15) NULL,
  `price-per-night` INT NULL,
  `has-seaview` VARCHAR(45) NULL,
  `breakfast-included` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`user_roles` (
  `id` INT NOT NULL,
  `role-name` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`users` (
  `id` INT NOT NULL,
  `login` VARCHAR(15) NULL,
  `password` VARCHAR(15) NULL,
  `name` VARCHAR(45) NULL,
  `surname` VARCHAR(45) NULL,
  `e-mail` VARCHAR(20) NULL,
  `country` VARCHAR(15) NULL,
  `telephone-number` VARCHAR(15) NULL,
  `user_roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_user_roles1_idx` (`user_roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_roles1`
    FOREIGN KEY (`user_roles_id`)
    REFERENCES `hotel`.`user_roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`requests` (
  `id` INT NOT NULL,
  `category` VARCHAR(15) NULL,
  `max-persons` INT NULL,
  `start-date` DATE NULL,
  `end-date` DATE NULL,
  `status` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requests_guests1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_requests_guests1`
    FOREIGN KEY (`users_id`)
    REFERENCES `hotel`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`rooms_has_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`rooms_has_requests` (
  `id` INT NOT NULL,
  `status` VARCHAR(15) NULL,
  `rooms_id` INT NOT NULL,
  `requests_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rooms_has_requests_rooms1_idx` (`rooms_id` ASC) VISIBLE,
  INDEX `fk_rooms_has_requests_requests1_idx` (`requests_id` ASC) VISIBLE,
  CONSTRAINT `fk_rooms_has_requests_rooms1`
    FOREIGN KEY (`rooms_id`)
    REFERENCES `hotel`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rooms_has_requests_requests1`
    FOREIGN KEY (`requests_id`)
    REFERENCES `hotel`.`requests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`bookings` (
  `id` INT NOT NULL,
  `real-start-date` DATE NULL,
  `real-end-date` DATE NULL,
  `rooms_has_requests_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookings_rooms_has_requests1_idx` (`rooms_has_requests_id` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_rooms_has_requests1`
    FOREIGN KEY (`rooms_has_requests_id`)
    REFERENCES `hotel`.`rooms_has_requests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`bills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel`.`bills` (
  `id` INT NOT NULL,
  `total-amount` INT NULL,
  `status` VARCHAR(45) NULL,
  `bookings_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bills_bookings1_idx` (`bookings_id` ASC) VISIBLE,
  CONSTRAINT `fk_bills_bookings1`
    FOREIGN KEY (`bookings_id`)
    REFERENCES `hotel`.`bookings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
